### ISSUE TITLE
Xbee

### ISSUE THREAD

**Issue by martin9115** [vogler/smart-home#6]
Hi can we connect xbee modules with zigbee2mqtt? Can we visualize the network topology?

**Comment by vogler** [comment]
This repo is just the config for my home. Why are you asking here instead of at zigbee2mqtt (or better yet just check their docs)?

zigbee2mqtt has a network map in its frontend: https://www.zigbee2mqtt.io/information/frontend.html
Xbee is listed under [supported devices](https://www.zigbee2mqtt.io/information/supported_devices.html#digi) but not under [supported adapters](https://www.zigbee2mqtt.io/information/supported_adapters.html).
